maps/de_dust2_2x2.bsp
maps/de_dust2_2x2.res
halflife.wad
cs_dust.wad
models/mil_crategibs.mdl
gfx/env/Desbk.tga
gfx/env/Desdn.tga
gfx/env/Desft.tga
gfx/env/Deslf.tga
gfx/env/Desrt.tga
gfx/env/Desup.tga
overviews/de_dust2_2x2.bmp
overviews/de_dust2_2x2.txt
