maps/de_russia_2x2.bsp
maps/de_russia_2x2.res
halflife.wad
liquids.wad
spraypaint.wad
ajawad.wad
cached.wad
cs_assault.wad
cs_cbble.wad
cs_dust.wad
cstraining.wad
cstrike.wad
de_aztec.wad
decals.wad
torntextures.wad
tswad.wad
gfx/env/TrainYardBk.tga
gfx/env/TrainYardDn.tga
gfx/env/TrainYardFt.tga
gfx/env/TrainYardLf.tga
gfx/env/TrainYardRt.tga
gfx/env/TrainYardUp.tga
overviews/de_russia_2x2.bmp
overviews/de_russia_2x2.txt
