//cs_bbicotka.wad
//cs_bikini.wad
//cs_estate.wad
//de_rats_caravan.wad
//pldecal.wad
//rats2k4.wad
maps/de_rats_1337.bsp
maps/de_rats_1337.res
chateau.wad
halflife.wad
liquids.wad
gfx/env/tsccity_bk.tga
gfx/env/tsccity_dn.tga
gfx/env/tsccity_ft.tga
gfx/env/tsccity_lf.tga
gfx/env/tsccity_rt.tga
gfx/env/tsccity_up.tga
sound/ambience/steamjet1.wav
sprites/spotlight01.spr
overviews/de_rats_1337.bmp
overviews/de_rats_1337.txt
