maps/de_westwood.bsp
maps/de_westwood.res
halflife.wad
itsitaly.wad
gfx/env/2desertbk.tga
gfx/env/2desertdn.tga
gfx/env/2desertft.tga
gfx/env/2desertlf.tga
gfx/env/2desertrt.tga
gfx/env/2desertup.tga
sound/ambience/guit1.wav
sound/nm_goodbadugly.wav
overviews/de_westwood.bmp
overviews/de_westwood.txt
