maps/cs_1337_assault.bsp
maps/cs_1337_assault.res
cs_assault.wad
decals.wad
gfx.wad
halflife.wad
liquids.wad
xeno.wad
gfx/env/city1bk.tga
gfx/env/city1dn.tga
gfx/env/city1ft.tga
gfx/env/city1lf.tga
gfx/env/city1rt.tga
gfx/env/city1up.tga
models/hostage.mdl
overviews/cs_1337_assault.bmp
overviews/cs_1337_assault.txt
