maps/cs_rio.bsp
maps/cs_rio.res
halflife.wad
cs_bdog.wad
cstrike.wad
decals.wad
models/aflock.mdl
models/controller.mdl
models/hostage.mdl
gfx/env/riobk.tga
gfx/env/riodn.tga
gfx/env/rioft.tga
gfx/env/riolf.tga
gfx/env/riort.tga
gfx/env/rioup.tga
sound/ambience/bezerra.wav
sound/ambience/cv.wav
sound/ambience/novela.wav
sound/ambience/rua1.wav
sound/ambience/rua3.wav
sound/debris/pushbox1.wav
sound/debris/pushbox2.wav
sound/debris/pushbox3.wav
sound/misc/apito.wav
sound/misc/apito2.wav
sound/fvox/one.wav
sound/fvox/three.wav
sound/fvox/two.wav
sound/weapons/ric1.wav
sound/weapons/ric2.wav
sound/weapons/ric4.wav
sprites/zbeam6.spr
overviews/cs_rio.bmp
overviews/cs_rio.txt
