maps/de_2x2dust.bsp
maps/de_2x2dust.res
cs_dust.wad
halflife.wad
de_storm.wad
gfx/env/Desbk.tga
gfx/env/Desdn.tga
gfx/env/Desft.tga
gfx/env/Deslf.tga
gfx/env/Desrt.tga
gfx/env/Desup.tga
overviews/de_2x2dust.bmp
overviews/de_2x2dust.txt
