maps/de_dust2_2x2_b_new.bsp
maps/de_dust2_2x2_b_new.res
chateau.wad
cs_dust.wad
cstrike.wad
decals.wad
halflife.wad
gfx/env/Desbk.tga
gfx/env/Desdn.tga
gfx/env/Desft.tga
gfx/env/Deslf.tga
gfx/env/Desrt.tga
gfx/env/Desup.tga
models/mil_crategibs.mdl
overviews/de_dust2_2x2_b_new.bmp
overviews/de_dust2_2x2_b_new.txt
