maps/de_dust4ever.bsp
maps/de_dust4ever.res
cs_dust.wad
cstrike.wad
decals.wad
halflife.wad
gfx/env/Desbk.tga
gfx/env/Desdn.tga
gfx/env/Desft.tga
gfx/env/Deslf.tga
gfx/env/Desrt.tga
gfx/env/Desup.tga
models/metalplategibs_green.mdl
overviews/de_dust4ever.bmp
overviews/de_dust4ever.txt
