maps/de_rats.bsp
maps/de_rats.res
cs_747.wad
cs_bdog.wad
halflife.wad
xeno.wad
gfx/env/2desertbk.tga
gfx/env/2desertdn.tga
gfx/env/2desertft.tga
gfx/env/2desertlf.tga
gfx/env/2desertrt.tga
gfx/env/2desertup.tga
models/metalplategibs.mdl
sound/ambience/steamjet1.wav
sprites/spotlight01.spr
overviews/de_rats.bmp
overviews/de_rats.txt
