maps/de_scud.bsp
maps/de_scud.res
halflife.wad
cs_dust.wad
cstrike.wad
decals.wad
gfx/env/desertbk.tga
gfx/env/desertdn.tga
gfx/env/desertft.tga
gfx/env/desertlf.tga
gfx/env/desertrt.tga
gfx/env/desertup.tga
sound/ambience/biggun3.wav
sound/ambience/computalk1.wav
sound/ambience/crickets.wav
sound/ambience/drips.wav
sound/ambience/tankidle2.wav
sound/ambience/waterfall3.wav
sprites/fire.spr
sprites/muzzleflash2.spr
overviews/de_scud.bmp
overviews/de_scud.txt
