maps/fy_pool_day.bsp
maps/fy_pool_day.res
gfx/env/desertbk.tga
gfx/env/desertdn.tga
gfx/env/desertft.tga
gfx/env/desertlf.tga
gfx/env/desertrt.tga
gfx/env/desertup.tga
sound/ambience/sprayer.wav
overviews/fy_pool_day.bmp
overviews/fy_pool_day.txt
