maps/mini_dust2.bsp
maps/mini_dust2.res
cs_dust.wad
cstrike.wad
decals.wad
halflife.wad
gfx/env/Desbk.tga
gfx/env/Desdn.tga
gfx/env/Desft.tga
gfx/env/Deslf.tga
gfx/env/Desrt.tga
gfx/env/Desup.tga
overviews/mini_dust2.bmp
overviews/mini_dust2.txt
