maps/cs_paris.bsp
maps/cs_paris.res
paris.wad
gfx/env/parisbk.tga
gfx/env/parisdn.tga
gfx/env/parisft.tga
gfx/env/parislf.tga
gfx/env/parisrt.tga
gfx/env/parisup.tga
models/hostage.mdl
models/cs_paris/cs_paris_bar.mdl
models/cs_paris/cs_paris_fass.mdl
models/cs_paris/cs_paris_heli.mdl
models/cs_paris/cs_paris_kiss.mdl
models/cs_paris/cs_paris_roof.mdl
models/cs_paris/cs_paris_seat.mdl
models/cs_paris/cs_paris_table01.mdl
models/cs_paris/cs_paris_table02.mdl
models/cs_paris/cs_paris_truck.mdl
models/cs_paris/cs_paris_umbrella.mdl
models/cs_paris/wb_glas.spr
sound/cs_paris/paris_atmo.wav
sound/cs_paris/paris_heli.wav
overviews/cs_paris.bmp
overviews/cs_paris.txt
