//a_bricks.wad
//a_roofs.wad
//a_woods.wad
//czde_inferno.wad
//de_chernobyl.wad
//de_forge.wad
//de_gothicmanor.wad
//de_inf.wad
//de_odessamama.wad
//dm_oc.wad
//oc2.wad
//orange.wad
//rrstar.wad
//spay_edition_1.wad
maps/de_oC2.bsp
maps/de_oC2.res
decals.wad
halflife.wad
gfx/env/sp_zavod_bk.tga
gfx/env/sp_zavod_dn.tga
gfx/env/sp_zavod_ft.tga
gfx/env/sp_zavod_lf.tga
gfx/env/sp_zavod_rt.tga
gfx/env/sp_zavod_up.tga
overviews/de_oC2.txt
overviews/de_oC2.bmp
